2025-10-17 05:37:07,089 [processing](INFO): Initializing backseat process (pilot lrauv based on marl)
2025-10-17 05:37:07,346 [Logger](CRITICAL): Uncaught exception
Traceback (most recent call last):
  File "./backseat_app/main.py", line 111, in <module>
    main()
  File "./backseat_app/main.py", line 105, in main
    backseat_app = BackseatApp(lc, cfg)
  File "./backseat_app/main.py", line 36, in __init__
    self.marl_processor = MarlProcessor(lcm_instance, self.cfg)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/processing.py", line 56, in __init__
    self.rl_tracking = TargetTracking(marl_method = self.marl_method)
  File "/home/maiv/lrauv_sim/lrauv-backseat-marl/backseat_app/utils.py", line 829, in __init__
    self.agents_range = np.zeros([self.num_target,self.num_agents])
AttributeError: 'TargetTracking' object has no attribute 'num_target'
