2025-10-09 18:14:08,813 [AppConfig](INFO): Reading configuration file: ./backseat_app/config/app_cfg_tethys.yml
2025-10-09 18:14:08,815 [Supervisor](INFO): Creating Supervisor.
2025-10-09 18:14:08,816 [Supervisor](INFO): Log folder created at: /home/maiv/lrauv_sim/lrauv-backseat-marl/logs/20251009T181408.
2025-10-09 18:14:08,816 [Supervisor](INFO): Starting lcm-log with cmd: lcm-logger -c '.*' --increment --split-mb=25 --quiet /home/maiv/lrauv_sim/lrauv-backseat-marl/logs/20251009T181408/lcmlog
2025-10-09 18:14:08,818 [Supervisor](INFO): Adding data request for: WetLabsBB2FL.mass_concentration_of_chlorophyll_in_sea_water
2025-10-09 18:14:08,819 [Supervisor](INFO): Adding data request for: NAL9602.latitude_fix
2025-10-09 18:14:08,819 [Supervisor](INFO): Adding data request for: depth
2025-10-09 18:14:08,819 [Supervisor](INFO): Adding data request for: NAL9602.longitude_fix
2025-10-09 18:14:08,819 [Supervisor](INFO): Adding data request for: DAT.enableBroadcast
2025-10-09 18:14:08,819 [Supervisor](INFO): Adding data request for: azimuth_vehicleFrame
2025-10-09 18:14:08,819 [Supervisor](INFO): Adding data request for: latitude
2025-10-09 18:14:08,820 [Supervisor](INFO): Adding data request for: longitude
2025-10-09 18:14:08,820 [processing](INFO): Initializing backseat process (pilot lrauv based on marl)
2025-10-09 18:14:08,846 [Listener](INFO): Listening on LCM channel: bsd_command
2025-10-09 18:14:08,846 [Listener](INFO): Listening on LCM channel: Universal
2025-10-09 18:14:08,846 [Listener](INFO): Listening on LCM channel: DAT
2025-10-09 18:14:11,348 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:11,348 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:11,348 [DataRequester](INFO): Requesting data from LRAUV.
2025-10-09 18:14:11,349 [Publisher](ERROR): Failed to publish LCM msg 4. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:11,349 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:13,852 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:13,852 [Publisher](ERROR): Failed to publish LCM msg 5. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:13,852 [Publisher](ERROR): Failed to publish LCM msg 6. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:13,853 [Publisher](ERROR): Failed to publish LCM msg 8. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:13,853 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:16,355 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:16,355 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:16,355 [Publisher](ERROR): Failed to publish LCM msg 9. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:16,356 [Publisher](ERROR): Failed to publish LCM msg 10. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:16,356 [Publisher](ERROR): Failed to publish LCM msg 12. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:16,356 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:18,858 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:18,858 [Publisher](ERROR): Failed to publish LCM msg 13. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:18,858 [Publisher](ERROR): Failed to publish LCM msg 14. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:18,859 [Publisher](ERROR): Failed to publish LCM msg 16. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:18,859 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:21,361 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:21,361 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:21,361 [Publisher](ERROR): Failed to publish LCM msg 17. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:21,362 [Publisher](ERROR): Failed to publish LCM msg 18. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:21,362 [Publisher](ERROR): Failed to publish LCM msg 20. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:21,362 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:23,864 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:23,864 [Publisher](ERROR): Failed to publish LCM msg 21. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:23,865 [Publisher](ERROR): Failed to publish LCM msg 22. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:23,865 [Publisher](ERROR): Failed to publish LCM msg 24. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:23,865 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:26,367 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:26,367 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:26,368 [Publisher](ERROR): Failed to publish LCM msg 25. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:26,368 [Publisher](ERROR): Failed to publish LCM msg 26. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:26,368 [Publisher](ERROR): Failed to publish LCM msg 28. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:26,368 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:28,870 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:28,870 [Publisher](ERROR): Failed to publish LCM msg 29. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:28,870 [Publisher](ERROR): Failed to publish LCM msg 30. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:28,871 [Publisher](ERROR): Failed to publish LCM msg 32. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:28,871 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:31,373 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:31,373 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:31,374 [Publisher](ERROR): Failed to publish LCM msg 33. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:31,374 [Publisher](ERROR): Failed to publish LCM msg 34. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:31,374 [Publisher](ERROR): Failed to publish LCM msg 36. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:31,374 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:33,876 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:33,876 [Publisher](ERROR): Failed to publish LCM msg 37. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:33,877 [Publisher](ERROR): Failed to publish LCM msg 38. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:33,877 [Publisher](ERROR): Failed to publish LCM msg 40. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:33,877 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:36,379 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:36,379 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:36,379 [Publisher](ERROR): Failed to publish LCM msg 41. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:36,380 [Publisher](ERROR): Failed to publish LCM msg 42. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:36,380 [Publisher](ERROR): Failed to publish LCM msg 44. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:36,380 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:38,882 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:38,882 [Publisher](ERROR): Failed to publish LCM msg 45. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:38,882 [Publisher](ERROR): Failed to publish LCM msg 46. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:38,883 [Publisher](ERROR): Failed to publish LCM msg 48. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:38,883 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:41,385 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:41,385 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:41,385 [Publisher](ERROR): Failed to publish LCM msg 49. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:41,386 [Publisher](ERROR): Failed to publish LCM msg 50. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:41,386 [Publisher](ERROR): Failed to publish LCM msg 52. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:41,386 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:43,888 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:43,888 [Publisher](ERROR): Failed to publish LCM msg 53. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:43,888 [Publisher](ERROR): Failed to publish LCM msg 54. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:43,889 [Publisher](ERROR): Failed to publish LCM msg 56. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:43,889 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:46,391 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:46,391 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:46,391 [Publisher](ERROR): Failed to publish LCM msg 57. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:46,392 [Publisher](ERROR): Failed to publish LCM msg 58. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:46,392 [Publisher](ERROR): Failed to publish LCM msg 60. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:46,392 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:48,894 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:48,894 [Publisher](ERROR): Failed to publish LCM msg 61. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:48,894 [Publisher](ERROR): Failed to publish LCM msg 62. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:48,895 [Publisher](ERROR): Failed to publish LCM msg 64. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:48,895 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:51,397 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:51,397 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:51,398 [Publisher](ERROR): Failed to publish LCM msg 65. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:51,398 [Publisher](ERROR): Failed to publish LCM msg 66. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:51,398 [Publisher](ERROR): Failed to publish LCM msg 68. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:51,398 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:53,900 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:53,900 [Publisher](ERROR): Failed to publish LCM msg 69. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:53,900 [Publisher](ERROR): Failed to publish LCM msg 70. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:53,901 [Publisher](ERROR): Failed to publish LCM msg 72. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:53,901 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:56,404 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:56,404 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:14:56,404 [Publisher](ERROR): Failed to publish LCM msg 73. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:56,405 [Publisher](ERROR): Failed to publish LCM msg 74. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:56,405 [Publisher](ERROR): Failed to publish LCM msg 76. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:56,405 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:14:58,907 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:14:58,907 [Publisher](ERROR): Failed to publish LCM msg 77. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:58,907 [Publisher](ERROR): Failed to publish LCM msg 78. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:58,908 [Publisher](ERROR): Failed to publish LCM msg 80. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:14:58,908 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:01,410 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:01,410 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:01,410 [Publisher](ERROR): Failed to publish LCM msg 81. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:01,411 [Publisher](ERROR): Failed to publish LCM msg 82. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:01,411 [Publisher](ERROR): Failed to publish LCM msg 84. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:01,411 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:03,913 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:03,914 [Publisher](ERROR): Failed to publish LCM msg 85. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:03,914 [Publisher](ERROR): Failed to publish LCM msg 86. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:03,914 [Publisher](ERROR): Failed to publish LCM msg 88. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:03,914 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:06,417 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:06,417 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:06,418 [Publisher](ERROR): Failed to publish LCM msg 89. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:06,418 [Publisher](ERROR): Failed to publish LCM msg 90. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:06,418 [Publisher](ERROR): Failed to publish LCM msg 92. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:06,418 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:08,920 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:08,920 [Publisher](ERROR): Failed to publish LCM msg 93. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:08,921 [Publisher](ERROR): Failed to publish LCM msg 94. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:08,921 [Publisher](ERROR): Failed to publish LCM msg 96. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:08,922 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:11,424 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:11,424 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:11,425 [DataRequester](INFO): Requesting data from LRAUV.
2025-10-09 18:15:11,425 [Publisher](ERROR): Failed to publish LCM msg 97. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:11,425 [Publisher](ERROR): Failed to publish LCM msg 98. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:11,425 [Publisher](ERROR): Failed to publish LCM msg 100. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:11,426 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:13,928 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:13,928 [Publisher](ERROR): Failed to publish LCM msg 101. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:13,928 [Publisher](ERROR): Failed to publish LCM msg 102. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:13,929 [Publisher](ERROR): Failed to publish LCM msg 104. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:13,929 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:16,431 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:16,431 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:16,432 [Publisher](ERROR): Failed to publish LCM msg 105. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:16,432 [Publisher](ERROR): Failed to publish LCM msg 106. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:16,432 [Publisher](ERROR): Failed to publish LCM msg 108. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:16,432 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:18,934 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:18,934 [Publisher](ERROR): Failed to publish LCM msg 109. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:18,935 [Publisher](ERROR): Failed to publish LCM msg 110. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:18,935 [Publisher](ERROR): Failed to publish LCM msg 112. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:18,935 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:21,438 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:21,438 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:21,438 [Publisher](ERROR): Failed to publish LCM msg 113. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:21,438 [Publisher](ERROR): Failed to publish LCM msg 114. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:21,439 [Publisher](ERROR): Failed to publish LCM msg 116. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:21,439 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:23,941 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:23,941 [Publisher](ERROR): Failed to publish LCM msg 117. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:23,941 [Publisher](ERROR): Failed to publish LCM msg 118. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:23,942 [Publisher](ERROR): Failed to publish LCM msg 120. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:23,942 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:26,444 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:26,444 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:26,444 [Publisher](ERROR): Failed to publish LCM msg 121. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:26,445 [Publisher](ERROR): Failed to publish LCM msg 122. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:26,445 [Publisher](ERROR): Failed to publish LCM msg 124. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:26,445 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:28,947 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:28,948 [Publisher](ERROR): Failed to publish LCM msg 125. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:28,948 [Publisher](ERROR): Failed to publish LCM msg 126. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:28,948 [Publisher](ERROR): Failed to publish LCM msg 128. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:28,948 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:31,451 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:31,451 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:31,451 [Publisher](ERROR): Failed to publish LCM msg 129. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:31,452 [Publisher](ERROR): Failed to publish LCM msg 130. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:31,452 [Publisher](ERROR): Failed to publish LCM msg 132. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:31,452 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:33,954 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:33,954 [Publisher](ERROR): Failed to publish LCM msg 133. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:33,954 [Publisher](ERROR): Failed to publish LCM msg 134. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:33,955 [Publisher](ERROR): Failed to publish LCM msg 136. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:33,955 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:36,457 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:36,457 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:36,458 [Publisher](ERROR): Failed to publish LCM msg 137. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:36,458 [Publisher](ERROR): Failed to publish LCM msg 138. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:36,458 [Publisher](ERROR): Failed to publish LCM msg 140. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:36,458 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:38,960 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:38,960 [Publisher](ERROR): Failed to publish LCM msg 141. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:38,960 [Publisher](ERROR): Failed to publish LCM msg 142. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:38,961 [Publisher](ERROR): Failed to publish LCM msg 144. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:38,961 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:41,463 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:41,463 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:41,463 [Publisher](ERROR): Failed to publish LCM msg 145. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:41,464 [Publisher](ERROR): Failed to publish LCM msg 146. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:41,464 [Publisher](ERROR): Failed to publish LCM msg 148. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:41,464 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:43,966 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:43,966 [Publisher](ERROR): Failed to publish LCM msg 149. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:43,967 [Publisher](ERROR): Failed to publish LCM msg 150. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:43,967 [Publisher](ERROR): Failed to publish LCM msg 152. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:43,967 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:46,469 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:46,469 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:46,469 [Publisher](ERROR): Failed to publish LCM msg 153. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:46,470 [Publisher](ERROR): Failed to publish LCM msg 154. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:46,470 [Publisher](ERROR): Failed to publish LCM msg 156. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:46,470 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:48,972 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:48,972 [Publisher](ERROR): Failed to publish LCM msg 157. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:48,972 [Publisher](ERROR): Failed to publish LCM msg 158. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:48,973 [Publisher](ERROR): Failed to publish LCM msg 160. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:48,973 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:51,475 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:51,475 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:51,476 [Publisher](ERROR): Failed to publish LCM msg 161. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:51,476 [Publisher](ERROR): Failed to publish LCM msg 162. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:51,476 [Publisher](ERROR): Failed to publish LCM msg 164. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:51,476 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:53,979 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:53,979 [Publisher](ERROR): Failed to publish LCM msg 165. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:53,979 [Publisher](ERROR): Failed to publish LCM msg 166. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:53,980 [Publisher](ERROR): Failed to publish LCM msg 168. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:53,980 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:56,482 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:56,482 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:15:56,483 [Publisher](ERROR): Failed to publish LCM msg 169. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:56,483 [Publisher](ERROR): Failed to publish LCM msg 170. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:56,483 [Publisher](ERROR): Failed to publish LCM msg 172. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:56,483 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:15:58,985 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:15:58,985 [Publisher](ERROR): Failed to publish LCM msg 173. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:58,985 [Publisher](ERROR): Failed to publish LCM msg 174. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:58,986 [Publisher](ERROR): Failed to publish LCM msg 176. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:15:58,986 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:01,488 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:01,488 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:01,489 [Publisher](ERROR): Failed to publish LCM msg 177. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:01,489 [Publisher](ERROR): Failed to publish LCM msg 178. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:01,489 [Publisher](ERROR): Failed to publish LCM msg 180. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:01,489 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:03,991 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:03,991 [Publisher](ERROR): Failed to publish LCM msg 181. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:03,992 [Publisher](ERROR): Failed to publish LCM msg 182. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:03,992 [Publisher](ERROR): Failed to publish LCM msg 184. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:03,992 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:06,494 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:06,494 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:06,494 [Publisher](ERROR): Failed to publish LCM msg 185. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:06,495 [Publisher](ERROR): Failed to publish LCM msg 186. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:06,495 [Publisher](ERROR): Failed to publish LCM msg 188. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:06,495 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:08,997 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:08,997 [Publisher](ERROR): Failed to publish LCM msg 189. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:08,997 [Publisher](ERROR): Failed to publish LCM msg 190. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:08,998 [Publisher](ERROR): Failed to publish LCM msg 192. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:08,998 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:11,500 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:11,500 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:11,500 [DataRequester](INFO): Requesting data from LRAUV.
2025-10-09 18:16:11,501 [Publisher](ERROR): Failed to publish LCM msg 193. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:11,501 [Publisher](ERROR): Failed to publish LCM msg 194. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:11,501 [Publisher](ERROR): Failed to publish LCM msg 196. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:11,501 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:14,003 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:14,003 [Publisher](ERROR): Failed to publish LCM msg 197. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:14,003 [Publisher](ERROR): Failed to publish LCM msg 198. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:14,004 [Publisher](ERROR): Failed to publish LCM msg 200. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:14,004 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:16,506 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:16,506 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:16,507 [Publisher](ERROR): Failed to publish LCM msg 201. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:16,507 [Publisher](ERROR): Failed to publish LCM msg 202. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:16,507 [Publisher](ERROR): Failed to publish LCM msg 204. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:16,507 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:19,009 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:19,009 [Publisher](ERROR): Failed to publish LCM msg 205. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:19,009 [Publisher](ERROR): Failed to publish LCM msg 206. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:19,010 [Publisher](ERROR): Failed to publish LCM msg 208. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:19,010 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:21,512 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:21,512 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:21,512 [Publisher](ERROR): Failed to publish LCM msg 209. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:21,513 [Publisher](ERROR): Failed to publish LCM msg 210. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:21,513 [Publisher](ERROR): Failed to publish LCM msg 212. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:21,513 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:24,015 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:24,015 [Publisher](ERROR): Failed to publish LCM msg 213. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:24,015 [Publisher](ERROR): Failed to publish LCM msg 214. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:24,016 [Publisher](ERROR): Failed to publish LCM msg 216. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:24,016 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:26,518 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:26,518 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:26,519 [Publisher](ERROR): Failed to publish LCM msg 217. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:26,519 [Publisher](ERROR): Failed to publish LCM msg 218. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:26,519 [Publisher](ERROR): Failed to publish LCM msg 220. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:26,520 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:29,022 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:29,022 [Publisher](ERROR): Failed to publish LCM msg 221. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:29,022 [Publisher](ERROR): Failed to publish LCM msg 222. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:29,023 [Publisher](ERROR): Failed to publish LCM msg 224. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:29,023 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:31,525 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:31,525 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:31,525 [Publisher](ERROR): Failed to publish LCM msg 225. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:31,526 [Publisher](ERROR): Failed to publish LCM msg 226. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:31,526 [Publisher](ERROR): Failed to publish LCM msg 228. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:31,526 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:34,029 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:34,029 [Publisher](ERROR): Failed to publish LCM msg 229. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:34,029 [Publisher](ERROR): Failed to publish LCM msg 230. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:34,029 [Publisher](ERROR): Failed to publish LCM msg 232. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:34,029 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:36,532 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:36,532 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:36,532 [Publisher](ERROR): Failed to publish LCM msg 233. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:36,533 [Publisher](ERROR): Failed to publish LCM msg 234. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:36,533 [Publisher](ERROR): Failed to publish LCM msg 236. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:36,533 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:39,035 [Listener](DEBUG): LCM listener timed out...
2025-10-09 18:16:39,035 [Publisher](ERROR): Failed to publish LCM msg 237. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:39,035 [Publisher](ERROR): Failed to publish LCM msg 238. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:39,036 [Publisher](ERROR): Failed to publish LCM msg 240. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:39,036 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:41,536 [Supervisor](DEBUG): Handling LCM msg on bsd_command.
2025-10-09 18:16:41,537 [Supervisor](INFO): Got command: shutdown.
2025-10-09 18:16:41,537 [Supervisor](DEBUG): Publishing heartbeat.
2025-10-09 18:16:41,537 [Publisher](ERROR): Failed to publish LCM msg 241. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:41,537 [Publisher](ERROR): Failed to publish LCM msg 242. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:41,537 [Publisher](ERROR): Failed to publish LCM msg 244. 
Traceback (most recent call last):
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/Publisher.py", line 139, in publish
    self.lc.publish(channel_name, self.msg.encode())
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 35, in encode
    self._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/LrauvLcmMessage.py", line 58, in _encode_one
    self.stringArrays[i0]._encode_one(buf)
  File "/home/maiv/.local/lib/python3.8/site-packages/lrauv/LCM/TethysLcmTypes/StringArray.py", line 39, in _encode_one
    __data_encoded = self.data[i0].encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
2025-10-09 18:16:41,537 [processing](INFO): IVAN. Published Observation State into Slate: 1284245816618
2025-10-09 18:16:41,537 [Listener](INFO): Unsubscribing from LCM channels.
2025-10-09 18:16:41,537 [main](INFO): Terminating.
